### ISSUE TITLE
Security Error

### ISSUE THREAD

**Issue by chrisspen** [PSPDFKit-labs/wasm-worker-example#3]
This code doesn't seem to work in any browser. I tested it in Chrome 83,  Firefox 80 and Brave 1.3, and they all throw errors.

Chrome:

    Uncaught DOMException: Failed to construct 'Worker': Script at 'file:///git/wasm_test/dist/5b2553d908807d385255.worker.js' cannot be accessed from origin 'null'.

Firefox:

    Security Error: Content at file:///git/wasm_test/index.html may not load data from file:///git/wasm_test/dist/5b2553d908807d385255.worker.js.

Brave:

    Uncaught DOMException: Failed to construct 'Worker': Script at 'file:///git/wasm_test/dist/5b2553d908807d385255.worker.js' cannot be accessed from origin 'null'.

This seems to be [by design](https://stackoverflow.com/questions/21408510/chrome-cant-load-web-worker).

You should consider recommending users install a minimal dev server like Flask or WS to host the index.html file.

**Comment by chrisspen** [comment]
Even using a minimal web server like [ws](https://github.com/lwsjs/local-web-server) doesn't seem to work.

Brave:

    5b2553d908807d385255.worker.js:1 Uncaught (in promise) RuntimeError: abort(You are getting _add on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js) at Error

Firefox:

    RuntimeError: abort(You are getting _add on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js) at N/r<@http://127.0.0.1:4321

Chrome:

    5b2553d908807d385255.worker.js:1 Uncaught (in promise) RuntimeError: abort(You are getting _add on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js) at Error

**Comment by ritz078** [comment]
Thanks for reporting this issue. 

> You should consider recommending users install a minimal dev server like Flask or WS to host the index.html file.

I have updated the Readme to address this. Thank you.

> Even using a minimal web server like ws doesn't seem to work.

This error was happening because of the newer version of emscripten. I have fixed the code so it should work now.
